Peak Phone Additions + Mild additions to Buildings
WorldOfDarknessXIII/World-of-Darkness-13 pull request #227
Opened 2024-11-20 06:38 UTC by Odisurin

## About The Pull Request
## Changelog
:cl:
add: Added stationary phones to clinic/millennium tower/pd reception, along with a clinic therapy room, multiple papers have been placed in important spots listing public numbers
![image](https://github.com/user-attachments/assets/b26fb3b2-8f2a-44ac-b121-da3b04c8a2d9)
![image](https://github.com/user-attachments/assets/8fe81c7d-5681-4064-ab1a-f35ac3f104e0)
![image](https://github.com/user-attachments/assets/2887cb6c-36e2-4694-b920-13fd9a566944)
![image](https://github.com/user-attachments/assets/f06799a7-5bef-4427-a855-b11f2701f61e)
add: Added gargoyles on ledges of the theatre and Church, along with reducing the blank space full of chairs to be a storage room and a auxiliary office space. And blinds for upper level privacy, cooler with three bloodbags in the basement of the chantry for rituals or brief feeding, water locals too
![image](https://github.com/user-attachments/assets/753633cb-586c-4bbd-ba66-19c48379eb45)
![image](https://github.com/user-attachments/assets/66b2fddd-d4fc-4243-8923-a94338250c6a)
![image](https://github.com/user-attachments/assets/f2c4a446-09f0-4bf8-9222-e539d2e7a513)
![image](https://github.com/user-attachments/assets/6f30d1f8-2633-44f4-8228-45277299e498)
Add: silver bullets (one box)/ revolver to chaplain dresser and extended the Chaplains office
![image](https://github.com/user-attachments/assets/91984a7a-13c8-43be-87e9-feb9d7d47c0d)
del: Removed double doors for the museum
fix: fixed the cleaner phone number
/:cl:

## Why It's Good For The Game
  These changes add more areas for Gargoyles to perch and observe instead of float, and the addition to phones being the four stationary phones means that you can just call the stationary listed on the important numbers paper at most buildings in order to get in contact with whomever is at the reception hopefully making calling police/clinic/cleaner players an involved process instead of being without a way to contact them.

 Ledges have also been added around two areas of the map such as the theatre and church for Gargoyle stalkers, Theatre now has less blank space

2024-11-23 12:57 UTC, CatandWet commented
I loaded this up in strongdmm a bit earlier in the week to check out and couldn't find much issue with it poking around at what got changed, so has my approval.

2024-11-23 20:19 UTC, lucifernix commented
You'll have to do something about the map conflict.

2024-11-23 23:38 UTC, Odisurin commented
There

2024-11-24 03:52 UTC, lucifernix commented
For some reason, this undoes the stuff I added in my admin buttons PR. Files admin.dm, admin_verbs.dm and SEVERAL other PR's that have been merged. So you'll have to... do something about it, too.

2024-11-24 03:53 UTC, lucifernix requested changes
Please fix the undoing of other PR's.

2024-11-24 03:54 UTC, Odisurin commented
Yeah.. I'll look into it later.

2024-11-24 23:24 UTC, Agateophobia commented
You sure you have this under control? Your changed files are uh... Jumbled up.

2024-11-25 01:53 UTC, closed without merging

2024-11-25 01:54 UTC, Odisurin commented
Ill just.. redo it again.. I guess