Adds XP to other jobs that were neglected & More
WorldOfDarknessXIII/World-of-Darkness-13 pull request #285
Opened 2024-12-05 05:44 UTC by AllCorruptingWyrm

## About The Pull Request

This PR picks up from https://github.com/WorldOfDarknessXIII/World-of-Darkness-13/pull/259 given it went stale and crunches the values just a little bit. This PR also adds xp to other jobs so people are encouraged and rewarded for playing them too! This also makes the grind a bit more manageable, too.

## Why It's Good For The Game

Done for reasons mentioned above.

## Changelog
:cl:
Baron and Prince get 10 xp
"Lieutenant" adjacent roles (Sheriff, Dealer, Zadruga, all the Primogen) get 7 xp on round end.
Seneschal and a couple lower roles get 6 xp on round end,
and foot roles get a base of 5 xp on round end.
The above get more (xp) if in the round longer.
/:cl:

2024-12-06 09:24 UTC, Agateophobia requested changes

2024-12-06 09:24 UTC, Agateophobia commented on code/controllers/subsystem/city_time.dm
> +									P.add_experience(5)
Dear god, this formatting is awful. Can't you make a newline break after every `||`?

2024-12-06 12:26 UTC, faaaay commented on code/controllers/subsystem/city_time.dm
> +									P.add_experience(5)
As I suggested on #259, maybe you could define an XP rate as a variable per-job and just call that variable?

2024-12-06 13:46 UTC, AllCorruptingWyrm commented on code/controllers/subsystem/city_time.dm
> +									P.add_experience(5)
> Dear god, this formatting is awful. Can't you make a newline break after every `||`? (it might break shit, but I would try it either way)

I tried and it gave me a lot of errors. If you could offer a code suggestion then I'll def change it, I'm not good at this coding stuff.

2024-12-11 20:43 UTC, faaaay commented
Is this stale?

2024-12-11 20:43 UTC, faaaay commented on code/controllers/subsystem/city_time.dm
> +									P.add_experience(5)
Is this currently stale?

2024-12-12 14:17 UTC, Agateophobia reviewed
This is just gonna cause elderpocalypse v2, I'd like to approve it, but it won't do anything of substance, other than just worsen the gen 7 max stat issue

2024-12-12 14:17 UTC, closed without merging

2024-12-12 16:14 UTC, faaaay commented
> This is just gonna cause elderpocalypse v2, I'd like to approve it, but it won't do anything of substance, other than just worsen the gen 7 max stat issue

Would you be willing to consider approving a PR raising XP values by _some_ amount (mostly for the roles that don't get much already), at the moment? 
The way I see it, part of the issue of the "elderpocalypse" is that it's easier for characters who already have plenty of XP/a low generation to _get_ XP, so people are disincentivised from playing multiple characters instead of putting all their rounds into one super-elder.

2024-12-14 00:46 UTC, wgtjunior743 commented
> > This is just gonna cause elderpocalypse v2, I'd like to approve it, but it won't do anything of substance, other than just worsen the gen 7 max stat issue
> 
> Would you be willing to consider approving a PR raising XP values by _some_ amount (mostly for the roles that don't get much already), at the moment? The way I see it, part of the issue of the "elderpocalypse" is that it's easier for characters who already have plenty of XP/a low generation to _get_ XP, so people are disincentivised from playing multiple characters instead of putting all their rounds into one super-elder.

I agree, making a char and making them strong takes a long long time,a very low amount of new players are joining, people keep making their chars stronger and don't stop playing them, i kept seeing the same players over and over again, xp gain is very low unless you play the perfect way to maximize xp gain and that ain't fun and there are power gamers anyways with 4-5 disciplines maxed and max stats, XP gain should be increased won't everyone get wiped anyways, let us enjoy the game.