[DRAFT] Throws Garou a bone & adjust some spells
WorldOfDarknessXIII/World-of-Darkness-13 pull request #314
Opened 2024-12-13 08:46 UTC by AllCorruptingWyrm

## About The Pull Request

After witnessing a complete and utter dumpster fire of a round, and numerous Garou acting smug and valiant that nothing can be done about them, something is getting done about them. This PR adjusts the healing costs and gnosis costs for a number of gifts to make them less spamable in combat.

also, some facts:

            if("Homid")
                character.auspice.gnosis = 1
                character.auspice.start_gnosis = 1
                character.auspice.base_breed = "Homid"
            if("Lupus")
                character.auspice.gnosis = 5
                character.auspice.start_gnosis = 5
                character.auspice.base_breed = "Lupus"
            if("Metis")
                character.auspice.gnosis = 3
                character.auspice.start_gnosis = 3
                character.auspice.base_breed = "Crinos"

Generally, you are going to hover around 3 gnosis, this makes gifts more impactful

## Why It's Good For The Game

To put it simply; Garou have provided a rather unpleasent environment on the server, due to how their crit is broken and their mechanics, they effectively get an aheal. This isn't good.

## Changelog
:cl:
Tweaks the power of some silver bullets, allowing them to have a higher probability of stunning and lowering gnosis.
Ups the stun time of silver bullets. does not increase damage.
Reimplements a cost for using the stoic pose, making it more of a get out of jail free card but gives them more time to be in stasis, you need to make it count.
Bloody feast and freezing wind get more of a gnosis cost.
Claws get a damage up in turn.
Longer up time cost on the aoe stun for glassies.

Compensates with the Set mummy form also getting a nerf too. Sorry setites but it had to be done.
/:cl:

2024-12-13 08:51 UTC, AllCorruptingWyrm commented
also nearly forgot; Rage heal restores more HP but has a MUCH higher cost, spamming it will eventually attrition you out.

2024-12-13 09:08 UTC, CatandWet commented
Buffs a broken skill, does a bunch of things that won't actually solve garou balance; it helps to know how things work before you change them.
Slightly higher rage costs are a good idea but the gnosis changes do not work; all homid born garou basically cannot use 80% of tribe gifts with these changes.

2024-12-13 09:23 UTC, AllCorruptingWyrm commented
"It helps to know things before you change them" really is not anything a staff member should be saying to contributors who are trying to make this place better, I know you had your PR so do it but dont get nasty with me because its a collaborative team effort.

2024-12-13 10:42 UTC, CatandWet commented
It was a little snappy, my bad. I do really appreciate you trying to get them toned down and I am happy to use your PR's changes and ideas because a fair bit of it is good and well founded.
Gnosis almost needs an entire rework before it can really be used as a resource for gifts.

2025-02-04 20:11 UTC, Metekillot requested changes

2025-02-04 20:11 UTC, Metekillot commented on code/modules/vtmb/werewolf/tribes.dm
>  				qdel(W)
move this into a proc that gets called with our timers

2025-02-04 20:11 UTC, Metekillot commented on code/modules/vtmb/werewolf/tribes.dm
>  				qdel(W)
Delete all of this and just make the initial check a || for these two conditions

2025-02-04 20:11 UTC, Metekillot commented on code/modules/wod13/ammostack.dm
> +			M.Stun(20)
hardstuns are a no from me, please just delete this bit for hardstunning someone with special ammo, stuns are lethal

2025-02-04 20:11 UTC, Metekillot commented on code/modules/wod13/ammostack.dm
> +			M.Stun(20)
see above

2025-02-04 20:11 UTC, Metekillot commented on code/modules/wod13/ammostack.dm
> +			M.Stun(20)
three! three hard stuns! ah ah ah! please remove

2025-02-04 20:11 UTC, Metekillot commented on code/modules/wod13/ammostack.dm
> +			M.Stun(20)
please remove this

2025-02-09 19:37 UTC, XanderDox commented
Are you still working on this @AllCorruptingWyrm ?

2025-02-22 11:10 UTC, XeonMations commented
Closed due to the author not having time.

2025-02-22 11:10 UTC, closed without merging