Phone Update part 2,  Call History, Delete Call History, Silence mode, Add Published contacts as contacts toggle.
WorldOfDarknessXIII/World-of-Darkness-13 pull request #346
Opened 2024-12-15 19:47 UTC by wgtjunior743

## About The Pull Request

Now you can see all your call history, from those who called you or if you called them , see in the pictures.
You can silence your phone and get zero noise, also toggle a new settings to auto add all published contacts to your contact list.
New button too, focused on settings, that was my first time touching tgui and react, so it ain't perfect, if someone with a better knowledge on that and wants to beautify , feel free to do it please.

The new settings button.
![new_phone](https://github.com/user-attachments/assets/186ae93e-267f-4691-b127-82fe6f9fec85)

The new options (this version i was working don't had the block, unblock etc)
![Uploading History_Del_History.PNG…]()

The toggles:
![sound_notifi](https://github.com/user-attachments/assets/c7f81fb8-7399-424b-b9f3-9dea69f08092)

Some examples for the call history:
![call_history_2](https://github.com/user-attachments/assets/e9b39bed-61af-45ff-8707-52e7d7a91589)
![call_history_1](https://github.com/user-attachments/assets/3b21c616-c71b-421c-a623-634a68aded77)

## Why It's Good For The Game

More stuff for phones, better phones.

## Changelog
:cl:
add: new settings button, changed abit of the tgui telephone code
add: new silence toggle at the settings button
add: new Toggle Published numbers as contacts at the settings button
add: new Call History and Delete History for the contact options
/:cl:

2024-12-16 07:46 UTC, lucifernix requested changes
phone_history.dm is not in tgstation.dme, it was never ticked on to be active in dreammaker.

Also, I get the following errors:

code\modules\vtmb\electronics\phones\phone.dm:558:error: ADDED_CONTACTS: undefined var
code\modules\vtmb\electronics\phones\phone.dm:559:error: ADDED_CONTACTS: undefined var
code\modules\vtmb\electronics\phones\phone.dm:345:error: else: 'else' clause without preceding 'if' statement

I was unable to get it to compile.

2024-12-16 11:48 UTC, wgtjunior743 commented
> phone_history.dm is not in tgstation.dme, it was never ticked on to be active in dreammaker.
> 
> Also, I get the following errors:
> 
> code\modules\vtmb\electronics\phones\phone.dm:558:error: ADDED_CONTACTS: undefined var code\modules\vtmb\electronics\phones\phone.dm:559:error: ADDED_CONTACTS: undefined var code\modules\vtmb\electronics\phones\phone.dm:345:error: else: 'else' clause without preceding 'if' statement
> 
> I was unable to get it to compile.

fixed that on the news commits, somehow i fucked up the identation when i was transfering the code from DM to github and ofcourse forgot one var, the new dm is added the tgstation.dme, forgot you had to do it manually here

2024-12-17 13:53 UTC, wgtjunior743 commented
> Hmm. I am still getting some warnings when trying to compile.
> 
> ![image](https://private-user-images.githubusercontent.com/35913671/396472023-81375edf-bf50-4ba9-bf41-72997268f1e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDA2MjYsIm5iZiI6MTczNDQ0MDMyNiwicGF0aCI6Ii8zNTkxMzY3MS8zOTY0NzIwMjMtODEzNzVlZGYtYmY1MC00YmE5LWJmNDEtNzI5OTcyNjhmMWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDEyNTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2OTgxMGE3Yjc1MTQ5MGIzNThiMmNlZGVmNTg4Mzg1NjdkYWI1MzE0YTZhZTU4ODhkYTNlM2E2YmY4NGI2OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gVuPqeK12XOtuPRNedBy6Ff6Y_YUWKL2dWtQcJRIW64) ![image](https://private-user-images.githubusercontent.com/35913671/396472099-37c11ac8-c526-4e34-99f6-5f9cb8cefad0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDA2MjYsIm5iZiI6MTczNDQ0MDMyNiwicGF0aCI6Ii8zNTkxMzY3MS8zOTY0NzIwOTktMzdjMTFhYzgtYzUyNi00ZTM0LTk5ZjYtNWY5Y2I4Y2VmYWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDEyNTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3OWU4OTNjNzFjODYzOWI2YWJjYzJlMzNiZDIwNzUzZDM3NzZiMzljNWQ4YzEyNzJlZWM1MzZmZjk2MzIzOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w4xNxKP_lG9mKGzXFcujdeJufcWAVNzkI_-lgb9aw94)

fixed on the new commit, it does the exactly same thing, just better byond wise and more friendly, to say the truth i had no idea you could run a for like that in byond, what i tried using was closer to java.
The warning is because before it was not searching for a specific datum but variables with those names on the list, it worked because it was not being used for any other stuff besides the phonehistory datum so ofcourse it would have that variables, but byond don't knew that and was saying "specify this type because it could have or not what you are asking for", that warning also does not show on DM for some ungodly reason.

2024-12-17 14:50 UTC, lucifernix commented on code/modules/vtmb/electronics/phones/phone.dm
> +						to_chat(usr, "<span class='notice'>The toggle of the published numbers in contacts is desactive.</span>")
```suggestion
						to_chat(usr, "<span class='notice'>The toggle of the published numbers in contacts is disabled.</span>")
```

2024-12-17 15:57 UTC, merged