Vampires now take extra damage from being on fire.
WorldOfDarknessXIII/World-of-Darkness-13 pull request #409
Opened 2024-12-29 04:12 UTC by boy2mantwicethefam

For every tick that a vampire is on fire they additionally take 4% of their max health in burn damage, with their weakness for fire already accounted for (the actual number is 2%). This is merely max health and NOT the total health of a vampire, which is an additional 200 while in a critical state (humans can get to -100, vampires can get to -200 but the last 100 are in torpor).

For some numbers, a theoretical 7th gen vampire with 6 Physique would have a max health of 375, which would make them take an additional 15 burn damage per tick while they're set on fire.

2024-12-29 12:20 UTC, Plaguewalker commented
They already take double burn damage in general.

2025-01-17 19:53 UTC, Metekillot requested changes

2025-01-17 19:53 UTC, Metekillot commented on code/modules/vtmb/kindred_species.dm
> +		H.adjustFireLoss(H.maxHealth * 0.02)
```suggestion
		H.adjustFireLoss(H.maxHealth * 0.10)
```
Being on fire for a vampire is an apocalypse-level "holy fuck" moment. Being lit on fire as a vampire should, in fact, also make the player go holy fuck. Being lit on fire as a vampire is one of the absolute last things that you want to happen to you ever and you should be going ridiculously out of your way to avoid it.

2025-01-17 23:36 UTC, boy2mantwicethefam commented on code/modules/vtmb/kindred_species.dm
> +		H.adjustFireLoss(H.maxHealth * 0.02)
They'd lose 20% max health every 2 seconds. Not a fun thing for the player behind the vampire to immediately collapse in a few seconds from one incendiary bullet.

2025-01-18 02:31 UTC, Metekillot commented on code/modules/vtmb/kindred_species.dm
> +		H.adjustFireLoss(H.maxHealth * 0.02)
> They'd lose 20% max health every 2 seconds. Not a fun thing for the player behind the vampire to immediately collapse in a few seconds from one incendiary bullet.

I'll meet you in the middle at 0.05 then. 10% every 2 seconds is BEEF, but if they think fast they MIGHT survive. Being lit on fire should be the absolute high-end oh shit factor for a vampire.

2025-01-18 05:06 UTC, Metekillot requested changes

2025-01-18 05:06 UTC, Metekillot commented on code/modules/vtmb/kindred_species.dm
> +		H.adjustFireLoss(H.maxHealth * 0.02)
```suggestion
		H.adjustFireLoss(H.maxHealth * 0.05)
```

2025-01-20 03:31 UTC, Metekillot approved these changes
after several of the admin team informed me that I was in fact Full Of Shit regarding my understanding of how much damage vamps take from fire in the lore, this is actually good to go.

2025-01-20 03:31 UTC, Metekillot approved these changes
after several of the admin team made it apparent to me that I was in fact Full Of Shit regarding what i thought i knew about vamps taking fire damage, this actually looks good

2025-01-24 09:26 UTC, merged